spring:
  application:
    name: team1-gateway

server:
  port: ${SERVER_PORT:10400}

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never

services:
  url:
    account: http://localhost:10413
    rule-engine: http://localhost:10406
    inventory: http://localhost:10411

security:
  jwt:
    public-paths: /api/auth/login, /api/accounts, /api/accounts/check-email, /api/accounts/check-pwd, /api/accounts/pwd/**, /api/core/invitations/**, /api/auth/.well-known/jwks.json
