services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: team1-filebeat
    user: root  # 도커 소켓, 컨테이너 로그 파일 접근 권한 필요
    command: ["--strict.perms=false"]   # filebeat.yml이 root 소유가 아니어서 파일 파싱 전 소유권 체크에 걸리는 문제 우회
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped
    networks: [team1-network]

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    container_name: team1-logstash
    environment:
      ES_HOST: ${ES_HOST}
      ES_USER: ${ES_USER}
      ES_PASSWORD: ${ES_PASSWORD}
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    restart: unless-stopped
    networks: [team1-network]

  grafana:
    image: grafana/grafana:latest
    container_name: team1-grafana
    ports:
      - "127.0.0.1:10410:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks: [team1-network]

  prometheus:
    image: prom/prometheus:latest
    container_name: team1-prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:10417:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks: [team1-network]

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: team1-zipkin
    ports:
      - "127.0.0.1:10418:9411"
    restart: unless-stopped
    networks: [team1-network]

networks:
  team1-network:
    external: true

volumes:
  grafana-data:
  prometheus-data: