filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: team1
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              multiline:
                pattern: '^\d{4}-\d{2}-\d{2}'
                negate: true
                match: after

output.logstash:
  hosts: ["team1-logstash:5044"]

logging.level: info
logging.to_stderr: true