input {
    beats {
        port => 5044
    }
}

filter {
    if [container][name] in ["team1-eureka-1", "team1-eureka-2", "team1-alert"] {
        dissect {
            mapping => {
                "message" => "%{log_timestamp->} %{log_level} %{} --- [%{}] [%{}] %{logger->} : %{log_message}"
            }
        }
    } else {
        dissect {
            mapping => {
                "message" => "%{log_timestamp->} %{log_level} %{} --- [%{}] [%{}] [%{trace_span}] %{logger->} : %{log_message}"
            }
        }
    }

    if [trace_span] =~ /-/ {
        dissect {
            mapping => { "trace_span" => "%{trace_id}-%{span_id}"}
        }
    }
}

output {
    elasticsearch {
        hosts => ["${ES_HOST}"]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        index => "team1-logs-%{+yyyy.MM.dd}"
    }

    if [log_level] == "ERROR" and [container][name] != "team1-alert" {
        http {
            url => "http://team1-alert:10419/webhook/logstash"
            http_method => "post"
            format => "json"
        }
    }
}