spring:
  application:
    name: team1-eureka

server:
  port: ${SERVER_PORT:10402}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:team1-eureka-1}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never