spring:
  application:
    name: team1-eureka

server:
  port: ${SERVER_PORT:10402}

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEER_URL}